on:
  push:
    branches: 
      - master 
    paths:
    - 'docs/**'
    - '!docs/book_examples/**'
  pull_request:
    branches: 
      - master
    paths:
    - 'docs/**'
    - '!docs/book_examples/**'

jobs:
  
  mdbook-build:
    runs-on: ubuntu-latest
    name: mdbook build
    steps:
      - uses: actions/checkout@v2

      - name: install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: install mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: '0.4.1'

     # - name: install linkcheck
     #   run: |
     #     curl -LSfs https://japaric.github.io/trust/install.sh | \
     #     sh -s -- --tag v0.7.0 --git Michael-F-Bryan/mdbook-linkcheck

      - name: mdbook build
        run: mdbook build
        working-directory: ./docs

