on:
  push:
    branches:
      - master
  pull_request:

jobs:
  update-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Generate Cargo.lock
        run: cargo generate-lockfile
        
      - id: cargo-deps
        name: Cache dependency crates
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git/db
          key: cargo-deps-${{ hashFiles('Cargo.lock') }}
        
      - if: steps.cargo-deps.outputs.cache-hit != 'true'
        name: Fetch dependencies
        run: cargo fetch --locked
        
      - name: Upload Cargo.lock
        uses: actions/upload-artifact@v2
        with:
          name: lockfile
          path: Cargo.lock
   
  rustfmt:
    runs-on: ubuntu-latest
    name: cargo fmt
    steps:
      - uses: actions/checkout@v2

      - name: install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: rustfmt
          override: true

      - name: cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  test-stable:
    needs: update-deps
    runs-on: ${{ matrix.os }}
    env:
      CARGO_INCREMENTAL: 0
    strategy:
      matrix:
        os: [macOS-latest, windows-2019, ubuntu-latest]
    name: cargo clippy+test
    steps:
      - uses: actions/checkout@v2

      - name: install libgtk-3-dev libx11-dev
        run: |
          sudo apt update
          sudo apt install libgtk-3-dev libx11-dev
        if: contains(matrix.os, 'ubuntu')

      - name: install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
          profile: minimal
          override: true

      - name: Download Cargo.lock
        uses: actions/download-artifact@v2
        with:
          name: lockfile
          
      - name: Restore dependency crates
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git/db
          key: cargo-deps-${{ hashFiles('Cargo.lock') }}
          
      - name: Cache target
        uses: actions/cache@v2
        with:
          path: target/
          key: ${{ matrix.os }}-target-${{ hashFiles('Cargo.lock') }}
          
      # Clippy packages in deeper-to-higher dependency order
      - name: cargo clippy druid-shell
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --manifest-path=druid-shell/Cargo.toml --locked --all-targets

      - name: cargo clippy druid
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --manifest-path=druid/Cargo.toml --locked --all-targets --features=svg,image,im

      - name: cargo clippy druid-derive
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --manifest-path=druid-derive/Cargo.toml --locked --all-targets

      - name: cargo clippy book examples
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --manifest-path=docs/book_examples/Cargo.toml --locked --all-targets

      # Test packages in deeper-to-higher dependency order
      - name: cargo test druid-shell
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path=druid-shell/Cargo.toml --locked

      - name: cargo test druid
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path=druid/Cargo.toml --locked --features=svg,image,im

      - name: cargo test druid-derive
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path=druid-derive/Cargo.toml --locked

      - name: cargo test book examples
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path=docs/book_examples/Cargo.toml --locked

      # After default features are done, also perform X11 clippy+testing on Linux.
      # This is better than a separate job because common dependencies are already built.
      - name: cargo clippy druid-shell (X11)
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --manifest-path=druid-shell/Cargo.toml --locked --all-targets --features=x11
        if: contains(matrix.os, 'ubuntu')

      - name: cargo clippy druid (X11)
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --manifest-path=druid/Cargo.toml --locked --all-targets --features=x11
        if: contains(matrix.os, 'ubuntu')

      - name: cargo test druid-shell (X11)
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path=druid-shell/Cargo.toml --locked --features=x11
        if: contains(matrix.os, 'ubuntu')

      - name: cargo test druid (X11)
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path=druid/Cargo.toml --locked --features=x11
        if: contains(matrix.os, 'ubuntu')

      - name: clean target
        run: cargo clean -p druid-shell -p druid -p druid-derive
